version: '3.8'

services:
  db:
    image: mysql:8.0.37
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookapi
      MYSQL_USER: app
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

  api:
    build: ./api
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    volumes:
      - ./api:/var/www/html/api

  client:
    build: ./client
    ports:
      - "3000:3000"  # Expose port 3000 for the client container
    env_file:
      - ./client/.env
    volumes:
      - ./client:/usr/src/app

  nginx:
    image: nginx:latest
    depends_on:
      - client
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx.crt:/etc/nginx/certs/nginx.crt:ro
      - ./nginx.key:/etc/nginx/certs/nginx.key:ro
volumes:
  mysql-data: {}
